"""Pydantic models used by the acceptance harness."""

from catalog_acceptance.models.contracts import (
    AcceptanceReport,
    AcceptanceSettings,
    CatalogItem,
    CheckResult,
    SeedManifest,
)
from catalog_acceptance.models.defender import DefenderEvidenceCapture
from catalog_acceptance.models.shared_challenges import (
    ApprovalObservation,
    BuildObservation,
    ColdStartQueryObservation,
    DatabaseFailureQueryObservation,
    DiagnosticSettingObservation,
    ErrorRateQueryObservation,
    GitHubRunObservation,
    HealthObservation,
    IdentityObservation,
    LoadEvidenceCapture,
    LoadRunObservation,
    MetricObservation,
    LatencyQueryObservation,
    ReplicaQueryObservation,
    RoleAssignmentEnumerationObservation,
    RevisionObservation,
    RollbackSafetyObservation,
    ScaleConfigurationObservation,
    SmokeObservation,
    TrafficObservation,
    WorkbookObservation,
)

__all__ = [
    "AcceptanceReport",
    "AcceptanceSettings",
    "ApprovalObservation",
    "BuildObservation",
    "CatalogItem",
    "CheckResult",
    "ColdStartQueryObservation",
    "DatabaseFailureQueryObservation",
    "DefenderEvidenceCapture",
    "DiagnosticSettingObservation",
    "ErrorRateQueryObservation",
    "GitHubRunObservation",
    "HealthObservation",
    "IdentityObservation",
    "LatencyQueryObservation",
    "LoadEvidenceCapture",
    "LoadRunObservation",
    "MetricObservation",
    "ReplicaQueryObservation",
    "RoleAssignmentEnumerationObservation",
    "RevisionObservation",
    "RollbackSafetyObservation",
    "ScaleConfigurationObservation",
    "SeedManifest",
    "SmokeObservation",
    "TrafficObservation",
    "WorkbookObservation",
]
